export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const FILTERED_PRODUCTS = 'FILTERED_PRODUCTS';
export const FILTERED_PRODUCTS_BY_PRICE = 'FILTERED_PRODUCTS_BY_PRICE';
